name: lando-mariadb-109
services:
  defaults:
    type: mariadb:10.9
  patch:
    type: mariadb:10.9.8
proxy:
  defaults:
    - hostname: db.lndo.site
      port: 3306
# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/mariadb": ../..
