name: lando-mariadb-112
services:
  defaults:
    type: mariadb:11.2
  patch:
    type: mariadb:11.2.3
proxy:
  defaults:
    - hostname: db.lndo.site
      port: 3306
# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/mariadb": ../..
