name: lando-mariadb-106
services:
  defaults:
    type: mariadb:10.6
  patch:
    type: mariadb:10.6.4
proxy:
  defaults:
    - hostname: db.lndo.site
      port: 3306
# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/mariadb": ../..
