name: lando-mariadb-114
services:
  database:
    type: mariadb:11.4
  patch:
    type: mariadb:11.4.6

proxy:
  database:
    - hostname: db.lndo.site
      port: 3306

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/mariadb": ../..
