name: lando-mariadbv4-1011
services:
  defaults:
    type: mariadb-v4:10.11
  patch:
    type: mariadb-v4:10.11.3-jammy

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/mariadb": ./../../
