name: lando-mariadb-103
services:
  defaults:
    type: mariadb:10.3
  patch:
    type: mariadb:10.3.32

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/mariadb": ./../../