name: lando-mariadb-116
services:
  database:
    type: mariadb:11.6
  patch:
    type: mariadb:11.6.2

proxy:
  database:
    - hostname: db.lndo.site
      port: 3306

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/mariadb": ../..
