name: lando-mariadb-101
services:
  defaults:
    type: mariadb:10.1
  patch:
    type: mariadb:10.1.45

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/mariadb": ./../../